// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_MinimumRcpp_RCPPEXPORTS_H_GEN_
#define RCPP_MinimumRcpp_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace MinimumRcpp {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("MinimumRcpp", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("MinimumRcpp", "_MinimumRcpp_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in MinimumRcpp");
            }
        }
    }

    inline DataFrame findParetoSet(SEXP idealPoints) {
        typedef SEXP(*Ptr_findParetoSet)(SEXP);
        static Ptr_findParetoSet p_findParetoSet = NULL;
        if (p_findParetoSet == NULL) {
            validateSignature("DataFrame(*findParetoSet)(SEXP)");
            p_findParetoSet = (Ptr_findParetoSet)R_GetCCallable("MinimumRcpp", "_MinimumRcpp_findParetoSet");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_findParetoSet(Shield<SEXP>(Rcpp::wrap(idealPoints)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<DataFrame >(rcpp_result_gen);
    }

}

#endif // RCPP_MinimumRcpp_RCPPEXPORTS_H_GEN_
