# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' findParetoSet
#' 
#' Will find the pareto set in a two dimensional spatial voting model given a set of ideal points.
#' 
#' The pareto set of a set of ideal points is the convex hull of that set of
#' alternatives. This function will take a set of ideal points and returns
#' their convex hull as a matrix of points. The points are listed down the rows in clockwise
#' or counterclockwise order with the first and last element in the matrix being the same ideal point.
#' 
#' @param idealPoints A numberOfVoters x numberOfDimensions matrix of ideal points.
#' 
#' @return The set of points that constitutes the pareto set of the set of alternatives. The points are listed down the rows in clockwise
#' or counterclockwise order with the first and last element in the matrix being the same ideal point.
#' 
#' @export
findParetoSet <- function(idealPoints) {
    .Call(`_MinimumRcpp_findParetoSet`, idealPoints)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_MinimumRcpp_RcppExport_registerCCallable', PACKAGE = 'MinimumRcpp')
})
